apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: sumanchatterjee21031987/cloud-gateway
        ports:
        - containerPort: 9090
        env:
        -  name: EUREKA_SERVER_ADDRESS
           valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm 
        -  name: CONFIG_SERVER_URL
           valueFrom:
            configMapKeyRef:
              key:  config-url
              name: config-cm

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 9090

